--- #YAML:1.0
name:               Mafia
version:            0.001
abstract:           easily moderate Mafia games
author:
    - Marius Gavrilescu <marius@ieval.ro>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    File::Basename:  0
    File::Slurp:     0
requires:
    perl:      5.014000
    Storable:  0
resources:
    repository:
        type:  git
        url:   http://git.ieval.ro/git/mafia.git
        web:   http://git.ieval.ro/?p=mafia.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
